#!/bin/bash

start() {
	ssserver -c /etc/shadowsocks/config.json -d start
}

stop() {
	ssserver -c /etc/shadowsocks/config.json -d stop
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "<Usage>: service shadowsocks {start|stop|restart}"
		exit 1
		;;
esac
